[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/bwmarrin/discordgo"
  version = "0.20.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.3"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.4.2"
